### ISSUE TITLE
.NET 5 -> .NET 6

### ISSUE THREAD

**Issue by mieliespoor** [Inedo/inedox-clair#3]
Given that .NET 5 was never an LTS version is seems to be a bad decision to drop support for dotnet 3.1 in favour of .NET 5.

Will .NET 5 be switched out in favour of .NET 6? [.NET 5 reaches EOL in May](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core).

**Comment by whatatripp** [comment]
Currently, only the Linux-edition of our products use .NET5 (changed from Mono); we will move all both Windows and Linux to .NET6 later this year across all products.
